spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://localhost:5432/shoppapp
    username: postgres
    password: Son01072004jqk!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
      enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  expiryMinutes: 5
  expiryDay: 14 #2 tuan
  accessKey: q/pUsru9/XIxLDSON1wVxV5CA1i1h/mTrFU6a0l6KaA=
  refreshKey: og9IMp84+s2W5uaheMxxAcEo9N5iyhzxlxFYIMIp4kI=