spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Son01072004jqk!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

jwt:
  secretKey: bvffjk@123